<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/01/07 09:14:42

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1;dbname=jobeet',
  'username' => 'jobeet',
  'password' => 12345,
  'name' => 'doctrine',
)),);
